spring:
  application:
    name: mindmentor-api
  datasource:
    url: jdbc:h2:mem:mindmentor
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8080

security:
  jwt:
    secret: "c2Vlbm1hc3Rlcm5hdGl2ZWNvcm5iaXJ0aG1ldGFscGVuY2lsZnVuZm91Z2h0aHVudGU="
    expiration-minutes: 60

logging:
  level:
    org.springframework.security: INFO
